<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>eu.tealhelix</groupId>
		<artifactId>howibuy-container</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>howibuy-dao-hibernate-reactive</artifactId>

	<name>HowiBuy: DAO implementation with Hibernate Reactive</name>
	<description>Implementation of the DAO interfaces of HowiBuy with Hibernate Reactive</description>

	<dependencies>
		<!-- PROJECT -->
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>howibuy-dao</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>howibuy-model</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>howibuy-services-model</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>tealhelix-common-dao-reactive</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>tealhelix-common-types</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- PROJECT TEST -->
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>tealhelix-common-dao-reactive-hibernate</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>tealhelix-common-testutils</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- SPECS -->
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
		</dependency>
		<dependency>
			<!-- needed by the Hibernate processor, do not include in runtime -->
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<!-- needed by the Hibernate processor, do not include in runtime -->
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<scope>provided</scope>
		</dependency>

		<!-- OTHER -->
		<dependency>
			<!-- needed by the Hibernate processor, do not include in runtime -->
			<groupId>org.antlr</groupId>
			<artifactId>antlr4-runtime</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-processor</artifactId>
			<scope>provided</scope>
		</dependency>

		<!-- TEST -->
		<dependency>
			<groupId>com.ongres.scram</groupId>
			<artifactId>scram-client</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-pg-client</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate.reactive</groupId>
			<artifactId>hibernate-reactive-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jdk14</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers-postgresql</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>dbupdate-howibuy</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.liquibase</groupId>
						<artifactId>liquibase-maven-plugin</artifactId>
						<version>${version.liquibase}</version>
						<configuration>
							<changeLogDirectory>src/main/resources</changeLogDirectory>
							<changeLogFile>db.changelog.xml</changeLogFile>
							<promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
							<url>${database.howibuy.jdbc.url}</url>
							<username>${database.howibuy.username}</username>
							<password>${database.howibuy.password}</password>
						</configuration>
						<executions>
							<execution>
								<id>liquibase-update</id>
								<phase>process-resources</phase>
								<goals>
									<goal>update</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
