<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>eu.tealhelix</groupId>
		<artifactId>howibuy-container</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>howibuy-jaxrs</artifactId>

	<name>HowiBuy: JAX-RS project</name>
	<description>JAX-RS implementations for HowiBuy</description>

	<dependencies>
		<!-- PROJECT -->
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>howibuy-service-interfaces</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>eu.tealhelix</groupId>
			<artifactId>tealhelix-common-web</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- SPECS -->
		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>mutiny</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.ws.rs</groupId>
			<artifactId>jakarta.ws.rs-api</artifactId>
		</dependency>

		<!-- OTHER -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>
	</dependencies>
</project>
